### ISSUE TITLE
current version crashes on load

### ISSUE THREAD

**Issue by florianschanda** [pyanodon/pypetroleumhandling#12]
This is before you can load any savegame, just on game load:

error message says
__pypetroleumhandling__/data.lua:12: __pypetroleumhandling__/prototypes/ores/tar-patch.lua:1: module __base__/prototypes/entity/demo-resource-autoplace not found; [...]

**Comment by rocfeather** [comment]
Looks like related to the changes:

> resource_autoplace_settings has been made public (require('resource-autoplace').resource_autoplace_settings) and the API improved. It will automatically allocate a unique resource index for each patch_set_name. 'patch_set_name' and 'autoplace_control_name' can be independently specified. 'seed1' can be specified as a parameter. The global function 'get_next_resource_index' is obsolete and has been deleted.

The fix appears to change the require to:

`local resource_autoplace = require('resource-autoplace')`

And remove the get_next_resource_index() calls in the resource_autoplace.resource_autoplace_settings{ }

This has to be done for the files in mods\pypetroleumhandling_1.2.1.zip\pypetroleumhandling_1.2.1\prototypes\ores

**Comment by kingarthur91** [comment]
fixed now

**Comment by florianschanda** [comment]
Awesome, thanks :)
