### ISSUE TITLE
global_item_replacer breaks recipes that contain "iron-gear-wheel" AND "small-parts-01" at the same time

### ISSUE THREAD

**Issue by MrJakobLaich** [pyanodon/pypetroleumhandling#74]
I have an inserter that has a recipe that has iron-plate, small-parts-01 as well as iron-gear-wheel
The global_item_replacer function, which seems to run in "data-updates.lua" in PyPetroleumHandling
The function seems to replace all "iron-gear-wheel" with "small-part-01"
![image](https://user-images.githubusercontent.com/40965742/225159085-7c9364a2-aa2a-4a66-bfc8-1c484e0c449b.png)
![image](https://user-images.githubusercontent.com/40965742/225159100-290d1765-87f9-46ea-abd9-d85108a1baf3.png)
![image](https://user-images.githubusercontent.com/40965742/225159137-34dc8455-af41-46a5-84c2-facf88f54681.png)

Solution:
Either add a remote function so I can add my own recipes as blacklist recipes, or change the function in some way so it doesn't break my recipes?

**Comment by notnotmelon** [comment]
I have added recipe.ignored_by_recipe_replacement in dev.

View the commit here: https://github.com/pyanodon/pycoalprocessing/commit/d2c34dedaadf5ad5e744de6804eba44d770003f9
