### ISSUE TITLE
NotNotMelon lied

### ISSUE THREAD

**Issue by Erkigmo** [pyanodon/pypetroleumhandling#77]
Only 4 lines are needed. Add this code to pYCoalTBA

data.lua

`local stone = table.deepcopy(data.raw.resource['angels-ore-1'])`
`stone.name = 'stone'`
`data:extend{stone}`

data-updates.lua
`
data.raw.resource['stone'] = nil
`

I'm not 100% sure if angels-ore-1 is the correct prototype name. Make sure to double check this.
Hope it helps!

_Originally posted by @notnotmelon in https://github.com/pyanodon/pypetroleumhandling/issues/76#issuecomment-1500445159_
            
![image](https://user-images.githubusercontent.com/122825731/230667739-43a8ce98-db77-4883-b6bc-5a719c9a9018.png)

**Comment by oorzkws** [comment]
> I'm not 100% sure if angels-ore-1 is the correct prototype name. Make sure to double check this.

He spoke the truth

**Comment by Erkigmo** [comment]
It was angels-ore1, and I replaced it. It still didn't work.
